# 05/27/2022
# generate floorplan and constraint file for 2nd order DSM but has no use
# currently

with open('fp of DSM_2nd.txt', 'w') as fileID:
    fileID.write(f'Guide: I0 {loc_Rin_lef[0]:.4f} {loc_Rin_lef[1]:.4f} {loc_Rin_lef[2]:.4f} {loc_Rin_lef[3]:.4f} 0\n')
    fileID.write(f'Guide: I1 {loc_Rin_rig[0]:.4f} {loc_Rin_rig[1]:.4f} {loc_Rin_rig[2]:.4f} {loc_Rin_rig[3]:.4f} 0\n')
    fileID.write(f'Guide: I2 {loc_CCO1_lef[0]:.4f} {loc_CCO1_lef[1]:.4f} {loc_CCO1_lef[2]:.4f} {loc_CCO1_lef[3]:.4f} 0\n')
    fileID.write(f'Guide: I3 {loc_CCO1_rig[0]:.4f} {loc_CCO1_rig[1]:.4f} {loc_CCO1_rig[2]:.4f} {loc_CCO1_rig[3]:.4f} 0\n')
    fileID.write(f'Guide: I4 {loc_PFD[0]:.4f} {loc_PFD[1]:.4f} {loc_PFD[2]:.4f} {loc_PFD[3]:.4f} 0\n')
    fileID.write(f'Guide: I5 {loc_CCO2_lef[0]:.4f} {loc_CCO2_lef[1]:.4f} {loc_CCO2_lef[2]:.4f} {loc_CCO2_lef[3]:.4f} 0\n')
    fileID.write(f'Guide: I6 {loc_CCO2_rig[0]:.4f} {loc_CCO2_rig[1]:.4f} {loc_CCO2_rig[2]:.4f} {loc_CCO2_rig[3]:.4f} 0\n')
    fileID.write(f'Guide: I7 {loc_QUAN_lef[0]:.4f} {loc_QUAN_lef[1]:.4f} {loc_QUAN_lef[2]:.4f} {loc_QUAN_lef[3]:.4f} 0\n')
    fileID.write(f'Guide: I8 {loc_QUAN_rig[0]:.4f} {loc_QUAN_rig[1]:.4f} {loc_QUAN_rig[2]:.4f} {loc_QUAN_rig[3]:.4f} 0\n')
    fileID.write(f'Guide: I9 {loc_DAC_BUF_lef[0]:.4f} {loc_DAC_BUF_lef[1]:.4f} {loc_DAC_BUF_lef[2]:.4f} {loc_DAC_BUF_lef[3]:.4f} 0\n')
    fileID.write(f'Guide: I10 {loc_DAC_BUF_rig[0]:.4f} {loc_DAC_BUF_rig[1]:.4f} {loc_DAC_BUF_rig[2]:.4f} {loc_DAC_BUF_rig[3]:.4f} 0\n')
    fileID.write(f'Guide: I11 {loc_DAC_lef[0]:.4f} {loc_DAC_lef[1]:.4f} {loc_DAC_lef[2]:.4f} {loc_DAC_lef[3]:.4f} 0\n')
    fileID.write(f'Guide: I12 {loc_DAC_rig[0]:.4f} {loc_DAC_rig[1]:.4f} {loc_DAC_rig[2]:.4f} {loc_DAC_rig[3]:.4f} 0\n')

    fileID.write(f'Fence: PD0 {loc_Rin_lef[0]:.4f} {loc_Rin_lef[1]:.4f} {loc_Rin_lef[2]:.4f} {loc_Rin_lef[3]:.4f} 0\n')
    fileID.write(f'Fence: PD1 {loc_Rin_rig[0]:.4f} {loc_Rin_rig[1]:.4f} {loc_Rin_rig[2]:.4f} {loc_Rin_rig[3]:.4f} 0\n')
    fileID.write(f'Fence: PD2 {loc_CCO1_lef[0]:.4f} {loc_CCO1_lef[1]:.4f} {loc_CCO1_lef[2]:.4f} {loc_CCO1_lef[3]:.4f} 0\n')
    fileID.write(f'Fence: PD3 {loc_CCO1_rig[0]:.4f} {loc_CCO1_rig[1]:.4f} {loc_CCO1_rig[2]:.4f} {loc_CCO1_rig[3]:.4f} 0\n')
    fileID.write(f'Fence: PD4 {loc_PFD[0]:.4f} {loc_PFD[1]:.4f} {loc_PFD[2]:.4f} {loc_PFD[3]:.4f} 0\n')
    fileID.write(f'Fence: PD5 {loc_CCO2_lef[0]:.4f} {loc_CCO2_lef[1]:.4f} {loc_CCO2_lef[2]:.4f} {loc_CCO2_lef[3]:.4f} 0\n')
    fileID.write(f'Fence: PD6 {loc_CCO2_rig[0]:.4f} {loc_CCO2_rig[1]:.4f} {loc_CCO2_rig[2]:.4f} {loc_CCO2_rig[3]:.4f} 0\n')
    fileID.write(f'Fence: PD7 {loc_QUAN_lef[0]:.4f} {loc_QUAN_lef[1]:.4f} {loc_QUAN_lef[2]:.4f} {loc_QUAN_lef[3]:.4f} 0\n')
    fileID.write(f'Fence: PD8 {loc_QUAN_rig[0]:.4f} {loc_QUAN_rig[1]:.4f} {loc_QUAN_rig[2]:.4f} {loc_QUAN_rig[3]:.4f} 0\n')
    fileID.write(f'Fence: PD9 {loc_DAC_BUF_lef[0]:.4f} {loc_DAC_BUF_lef[1]:.4f} {loc_DAC_BUF_lef[2]:.4f} {loc_DAC_BUF_lef[3]:.4f} 0\n')
    fileID.write(f'Fence: PD10 {loc_DAC_BUF_rig[0]:.4f} {loc_DAC_BUF_rig[1]:.4f} {loc_DAC_BUF_rig[2]:.4f} {loc_DAC_BUF_rig[3]:.4f} 0\n')
    fileID.write(f'Fence: PD11 {loc_DAC_lef[0]:.4f} {loc_DAC_lef[1]:.4f} {loc_DAC_lef[2]:.4f} {loc_DAC_lef[3]:.4f} 0\n')
    fileID.write(f'Fence: PD12 {loc_DAC_rig[0]:.4f} {loc_DAC_rig[1]:.4f} {loc_DAC_rig[2]:.4f} {loc_DAC_rig[3]:.4f} 0\n')

with open('Constraint of DSM_2nd.txt', 'w') as fileID:
    fileID.write('</Constraints>\n')
    fileID.write(f'    <Constraint type="Guide" name="I0" llx={loc_Rin_lef[0]:.4f} lly={loc_Rin_lef[1]:.4f} urx={loc_Rin_lef[2]:.4f} ury={loc_Rin_lef[3]:.4f} nrBox=0 > \n')
    fileID.write('    </Constraint>\n')
    fileID.write(f'    <Constraint type="Guide" name="I1" llx={loc_Rin_rig[0]:.4f} lly={loc_Rin_rig[1]:.4f} urx={loc_Rin_rig[2]:.4f} ury={loc_Rin_rig[3]:.4f} nrBox=0 > \n')
    fileID.write('    </Constraint>\n')
    fileID.write(f'    <Constraint type="Guide" name="I2" llx={loc_CCO1_lef[0]:.4f} lly={loc_CCO1_lef[1]:.4f} urx={loc_CCO1_lef[2]:.4f} ury={loc_CCO1_lef[3]:.4f} nrBox=0 > \n')
    fileID.write('    </Constraint>\n')
    fileID.write(f'    <Constraint type="Guide" name="I3" llx={loc_CCO1_rig[0]:.4f} lly={loc_CCO1_rig[1]:.4f} urx={loc_CCO1_rig[2]:.4f} ury={loc_CCO1_rig[3]:.4f} nrBox=0 > \n')
    fileID.write('    </Constraint>\n')
    fileID.write(f'    <Constraint type="Guide" name="I4" llx={loc_PFD[0]:.4f} lly={loc_PFD[1]:.4f} urx={loc_PFD[2]:.4f} ury={loc_PFD[3]:.4f} nrBox=0 > \n')
    fileID.write('    </Constraint>\n')
    fileID.write(f'    <Constraint type="Guide" name="I5" llx={loc_CCO2_lef[0]:.4f} lly={loc_CCO2_lef[1]:.4f} urx={loc_CCO2_lef[2]:.4f} ury={loc_CCO2_lef[3]:.4f} nrBox=0 > \n')
    fileID.write('    </Constraint>\n')
    fileID.write(f'    <Constraint type="Guide" name="I6" llx={loc_CCO2_rig[0]:.4f} lly={loc_CCO2_rig[1]:.4f} urx={loc_CCO2_rig[2]:.4f} ury={loc_CCO2_rig[3]:.4f} nrBox=0 > \n')
    fileID.write('    </Constraint>\n')
    fileID.write(f'    <Constraint type="Guide" name="I7" llx={loc_QUAN_lef[0]:.4f} lly={loc_QUAN_lef[1]:.4f} urx={loc_QUAN_lef[2]:.4f} ury={loc_QUAN_lef[3]:.4f} nrBox=0 > \n')
    fileID.write('    </Constraint>\n')
    fileID.write(f'    <Constraint type="Guide" name="I8" llx={loc_QUAN_rig[0]:.4f} lly={loc_QUAN_rig[1]:.4f} urx={loc_QUAN_rig[2]:.4f} ury={loc_QUAN_rig[3]:.4f} nrBox=0 > \n')
    fileID.write('    </Constraint>\n')
    fileID.write(f'    <Constraint type="Guide" name="I9" llx={loc_DAC_BUF_lef[0]:.4f} lly={loc_DAC_BUF_lef[1]:.4f} urx={loc_DAC_BUF_lef[2]:.4f} ury={loc_DAC_BUF_lef[3]:.4f} nrBox=0 > \n')
    fileID.write('    </Constraint>\n')
    fileID.write(f'    <Constraint type="Guide" name="I10" llx={loc_DAC_BUF_rig[0]:.4f} lly={loc_DAC_BUF_rig[1]:.4f} urx={loc_DAC_BUF_rig[2]:.4f} ury={loc_DAC_BUF_rig[3]:.4f} nrBox=0 > \n')
    fileID.write('    </Constraint>\n')
    fileID.write(f'    <Constraint type="Guide" name="I11" llx={loc_DAC_lef[0]:.4f} lly={loc_DAC_lef[1]:.4f} urx={loc_DAC_lef[2]:.4f} ury={loc_DAC_lef[3]:.4f} nrBox=0 > \n')
    fileID.write('    </Constraint>\n')
    fileID.write(f'    <Constraint type="Guide" name="I12" llx={loc_DAC_rig[0]:.4f} lly={loc_DAC_rig[1]:.4f} urx={loc_DAC_rig[2]:.4f} ury={loc_DAC_rig[3]:.4f} nrBox=0 > \n')
    fileID.write('    </Constraint>\n')

    fileID.write(f'    <Constraint type="Fence" name="PD0" llx={loc_Rin_lef[0]:.4f} lly={loc_Rin_lef[1]:.4f} urx={loc_Rin_lef[2]:.4f} ury={loc_Rin_lef[3]:.4f} nrBox=0 > \n')
    fileID.write('    </Constraint>\n')
    fileID.write(f'    <Constraint type="Fence" name="PD1" llx={loc_Rin_rig[0]:.4f} lly={loc_Rin_rig[1]:.4f} urx={loc_Rin_rig[2]:.4f} ury={loc

